[package]
name = "rs-shell"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.11"
ntapi = { version = "0.4.1", features = ["impl-default"] }
winapi = "0.3.9"
signal-hook = "0.3.17"
regex = "1.10.2"
open = "5.0.1"
simple_logger = "4.3.0"
log = "0.4.20"
ctrlc = "3.4.1"
clap = { version = "4.4.11", features = ["derive"] }
syscalls = { git = "https://github.com/BlWasp/syscalls-rs.git", branch = "main",  features = ["_INDIRECT_"] }

[dependencies.windows-sys]
version = "0.52.0"
features = [
    "Win32_System_Memory",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Kernel",
    "Wdk_System_Threading"
]
